### ISSUE TITLE
Ollama url error when using windows

### ISSUE THREAD

**Issue by RexZhann** [asynchronous-flows/asyncflows#3]
When I was trying out the text_style_transfer.py, it always return a invalid url error, where the api_url became: 

http://localhost:11434\api\chat

I'm guessing it's a windows issue since it was all good on macOS
![屏幕截图 2024-06-04 185929](https://github.com/asynchronous-flows/asyncflows/assets/106326425/a1620fb4-c898-4bc4-883e-d4543168e227)

**Comment by irgolic** [comment]
Hi @RexZhann, thanks for opening this issue! Especially, thanks for testing on two platforms.

I think I know what's wrong, seems like the URL is being concatenated as if it were a Windows path.

**Comment by irgolic** [comment]
I've just released 0.1.7 with a fix for this.

Thanks again for the bug report!
