### ISSUE TITLE
Infinity feedback

### ISSUE THREAD

**Issue by michaelfeil** [asynchronous-flows/asyncflows#5]
Great work @irgolic !

Re: asyncflows/utils/transformers_utils.py

Got some feedback:

1. Infinity should have type checks. You can use 

```python
# from infinity_emb import AsyncEmbeddingEngine, EngineArgs
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from infinity_emb import AsyncEmbeddingEngine, EngineArgs

def fun(engine: "AsyncEmbeddingEngine"): # defered type eval
```

2. from infinity_emb import AsyncEngineArray
This could be useful for multiple engines / evals.

3. Start / shutdown:

I am not sure what you are trying here? You can shutdown the engine any time !

```
asyncio.create_task(
      shutdown_engine(log, keep_engine_alive_delay, model, engine)
  )
```
Maybe you are looking for a `engine_unused = asyncio.Event` + a counter that checks for eviction. Is that something you would like to have upstreamed?

**Comment by irgolic** [comment]
Hey @michaelfeil, nice to meet you, and thanks for the feedback!

<details>
<summary>
Re 1
</summary>

`infinity_emb` is an optional dependency, so I swapped out the top-level imports quickly. I've put the `if TYPE_CHECKING` clause in now, thanks for that.

</details>

<details>
<summary>
Re 2
</summary>

I see `AsyncEngineArray` was added recently, nice! I don't think it matches my use case exactly. I'm only ever instantiating the engine that's specified in the config of an embedding action, for example:

```yaml
  retrieval:
    action: retrieve
    model: sentence-transformers/all-mpnet-base-v2
    k: 5
    documents:
      var: texts
    query:
      var: question
```

There's never really a list of models being specified. If in the future we decide to optimize by spinning up all engines specified in the flow at the same time I think it'll come in handy.

</details>

<details>
<summary>
Re 3
</summary>

The reason I shut down the engine with a delay is, if multiple requests come flooding in within a short timespan (within the `keep_engine_alive_delay`, e.g., 5 seconds), it will serve all those requests without shutting down the engine. But as soon as the 5 seconds pass without any requests, it shuts down the engine and unloads the model.

If it this could be managed upstream, that'd be great! I suppose an `engine_unused` event would clean my code up. Not sure if you'd be tracking it any differently from how I'm doing it here.

An even cleaner way would be if `infinity_emb` maintained a repository of engines, and it would shut them down when they go unused, after a configurable delay. So there would be a `get_engine` method that would either construct a new engine, or return an already constructed one if the engine args match and the engine hasn't expired yet. That's the spirit of my `get_engine` function anyway.

</details>

Let me know if I misunderstood anything, or if I can provide more information.

Also, feel free to reach out [on Discord](https://discord.gg/AGZ6GrcJCh) or elsewhere; I'd love to talk :)

**Comment by michaelfeil** [comment]
Thanks! As you notice, infinity is more built for for server usecases - its a pretty heavy operation to load a model into ram! You comments to (3) were really helpful - I’ll think about if I should implement a shutdown safeguard / counter. 

Joined the discord
